export const GITHUB_ERROR_CODES = {
  AUTH_REQUIRED: 'GITHUB_AUTH_REQUIRED',
  TOKEN_INVALID: 'GITHUB_TOKEN_INVALID',
  CONNECTION_UNREADABLE: 'GITHUB_CONNECTION_UNREADABLE',
  CONNECTION_STORAGE_UNAVAILABLE: 'GITHUB_CONNECTION_STORAGE_UNAVAILABLE',
  ACCESS_FORBIDDEN: 'GITHUB_ACCESS_FORBIDDEN',
  RATE_LIMITED: 'GITHUB_RATE_LIMITED',
  UPSTREAM_UNAVAILABLE: 'GITHUB_UPSTREAM_UNAVAILABLE',
  RESPONSE_INVALID: 'GITHUB_RESPONSE_INVALID',
} as const;

export type GitHubErrorCode =
  (typeof GITHUB_ERROR_CODES)[keyof typeof GITHUB_ERROR_CODES];

export function isGitHubReconnectErrorCode(code: unknown) {
  return (
    code === GITHUB_ERROR_CODES.AUTH_REQUIRED ||
    code === GITHUB_ERROR_CODES.TOKEN_INVALID ||
    code === GITHUB_ERROR_CODES.CONNECTION_UNREADABLE
  );
}
